function IMypMyp2ScreenModule () {
    // No properties declared
}
module.exports = IMypMyp2ScreenModule;
var instance = IMypMyp2ScreenModule.prototype;
instance.addNewItem = function () {
    // AUTOGENERATED, COPY DON'T EDIT
    throw new Error("addNewItem is unimplemented");
};
 
/**
 * @param index {@link _.isNumber($0)}
 */
instance.itemSelected = function (index) {
    // AUTOGENERATED, COPY DON'T EDIT
    throw new Error("itemSelected is unimplemented");
};
 